
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rigarhwhsjbajtwwccoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZ2FyaHdoc2piYWp0d3djY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODk2NjYsImV4cCI6MjA1NjE2NTY2Nn0.2hbvjVB50n7oEeAwoBn-RuPRfn1JFJiFbebvS6lu8YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
